[package]
name = "morst"
version = "0.1.0"
authors = ["Micah Fitch <micahscopes@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.0"
float_duration = "0.3.3"
dispose = "0.3.1"
uid = "0.1.5"